### ISSUE TITLE
Release 0.3.6

### ISSUE THREAD

**Issue by wildintellect** [MAAP-Project/stac_ipyleaflet#125]
### Description

Due to #123 we need to cut a new release. This should happen with enough time for JPL to pull into the next MAAP workspace.
This was a very MAAP specific fix to default layers. Is there a way to decouple this from the main code?

@anilnatha when do you need the release by in order to make the next workspace upgrade?

**Comment by jjfrench** [comment]
@anilnatha , version 0.3.6 has been released

**Comment by anilnatha** [comment]
The team discussed this update a few moments ago and we will include this in our next release, in the interim, it would be best if we could advise affected users to update their workspace with this version manually as we are also attempting to address workspace versioning issues Laura has brought up.

CC: @gchang @sujen1412

**Comment by wildintellect** [comment]
@jjfrench can you document here the pip+git command for users to manually upgrade?

**Comment by jjfrench** [comment]
For installing version 0.3.6
```
%pip install --upgrade git+https://github.com/MAAP-Project/stac_ipyleaflet.git@0.3.6#egg-info=stac_ipyleaflet
```

**Comment by wildintellect** [comment]
Informed users https://github.com/orgs/MAAP-Project/discussions/883
