### ISSUE TITLE
`pystac_client` is missing from `requirements.txt`

### ISSUE THREAD

**Issue by emileten** [MAAP-Project/stac_ipyleaflet#29]
At the moment, if I follow the installation guidelines and try to run the demo notebook, I get the following error : 

![Screenshot 2023-02-20 at 4 10 39 PM](https://user-images.githubusercontent.com/45140658/220199177-2e8b06eb-de9a-4da8-bdc5-ebc832208e4a.png)

**Comment by wildintellect** [comment]
@emileten can you open a PR with the fix?
