### ISSUE TITLE
Epic: Discovery

### ISSUE THREAD

**Issue by zacharyDez** [MAAP-Project/stac_ipyleaflet#31]
### Description

As part of the project's new phase, we need to understand better the technical stack, deployment, and development process. We must also integrate the project into our design system and define the "jobs to be done" for end-users. In addition, we need to scope the intended changes for the project and create a link to Milestone 1, which will focus on documenting the current functionality.

### Tasks

- Gain familiarity with the technical stack, deployment process, and development workflow.
- Integrate the project into our design system and ensure it adheres to our style guide.
- Define the needs for end-users and document user personas.
- Scope the intended changes for the project and prioritize them based on user needs and business goals.

### Acceptance Criteria

- Technical stack, deployment process and development workflow are documented and understood by the team.
- The project is integrated into our design system and adheres to our style guide.
- User personas are documented, and we have a clear picture of their needs.
- Intended changes for the project are scoped and prioritized based on user needs and business goals.
- We have a plan on how to measure NPS and potentially assessing a baseline.

**Comment by zacharyDez** [comment]
Added acceptance criteria for measuring NPS.

**Comment by heidimok** [comment]
This is the internal discovery report. We can treat this as our deliverable for this phase (even though questions will continue to be brought up and answered as we move along). https://docs.google.com/presentation/d/1waJs6ylIHadGmWcXQ0n2kABii-838jXSMMQEe8FPoxA/edit#slide=id.g22d555303ed_0_21

After we review it together as a team we can close out this issue :)
