### ISSUE TITLE
Epic: Document existing tools

### ISSUE THREAD

**Issue by zacharyDez** [MAAP-Project/stac_ipyleaflet#32]
### Description

This epic aims to evaluate the current geospatial visualization tools used by MAAP, namely stac_ipyleaflet and leafmap, and compare them to other popular tools like Kepler, based on our use cases. The evaluation will consider factors like ease of use, performance, functionality, and compatibility with other libraries and technologies. The goal is to identify the best tool that meets our needs and improve the geospatial visualization experience for MAAP users.

### Tasks

- Conduct a thorough evaluation of stac_ipyleaflet and leafmap, including their features, performance, and compatibility with other technologies.
- Research and evaluate other geospatial visualization tools like Kepler, Mapbox, and ArcGIS Online, based on their features, performance, and compatibility with other technologies.
- Develop a set of use cases that reflect the common scenarios and workflows of MAAP users and test each tool's capabilities based on these use cases.
- Evaluate the ease of use and learning curve of each tool, based on the user's feedback and experience.
- Document the evaluation results, including a comparison matrix and a summary of pros and cons for each tool.
- Discuss the results with the MAAP development team and make a recommendation for the best geospatial visualization tool that meets our needs.

### Acceptance Criteria

- A thorough evaluation of stac_ipyleaflet and leafmap, and other alternatives such as Kepler.
- A set of use cases is developed and tested against each tool.
- The ease of use and learning curve of each tool are evaluated and documented.
- A comparison matrix and a summary of pros and cons for each tool are created and documented.
- The results of the evaluation are discussed with the MAAP development team and a recommendation for the best geospatial visualization tool is made.

**Comment by zacharyDez** [comment]
@abarciauskas-bgse updated based on your recent request. @emmalu maybe you can link your comparison document here?

**Comment by emmalu** [comment]
> @emmalu maybe you can link your comparison document here?

Better late than never!
![Screenshot 2023-04-18 at 8 31 17 AM](https://user-images.githubusercontent.com/18629881/232778064-921ba62f-a434-4e4f-87cf-de7a67215969.png)
