### ISSUE TITLE
Epic: Plan for documenting and extending existing tools to serve MAAP users

### ISSUE THREAD

**Issue by zacharyDez** [MAAP-Project/stac_ipyleaflet#34]
### Description

This epic focuses on planning for future work on the project based on the opportunities identified during the discovery and development process. This will involve defining future functionality and visualizing more kinds of data, among other tasks.

### Tasks

- Plan a workshop to brainstorm and define the future work for the project.
- Define future functionality based on opportunities identified during the project, such as styling layers and allowing users to add their data.
- Explore ways to achieve feature parity with similar tools in the market.
- Investigate visualizing more kinds of data beyond raster data, such as extensive point and Zarr data.
- Determine the feasibility and technical requirements for implementing the identified future work.
- Create a roadmap or plan for implementing future work.
- Document the outcomes of the workshop and the plan for future work.

### Acceptance Criteria

- A workshop is conducted, and future work is defined based on the opportunities identified during the project.
- Future functionality is defined and explored, including ways to achieve feature parity with similar tools in the market.
- Investigation of visualizing more kinds of data is conducted, and the feasibility and technical requirements are determined.
- Roadmap or plan for implementing the future work is created and documented.

**Comment by zacharyDez** [comment]
based on feedback from @abarciauskas-bgse : _This roadmap should include feedback from users on using leafmap and its downsides. This roadmap should include a priority for new features to add, such as the ability to visualize point cloud datasets or create a mosaic from a STAC catalog query._

**Comment by zacharyDez** [comment]
_Research and explore existing tools which might help us achieve those new features. For example, can we visualize point clouds with [kepler.gl](http://kepler.gl/) and how? To visualize mosaics from COGs we probably need titiler-pgstac, can we test that out?_

**Comment by heidimok** [comment]
https://docs.google.com/spreadsheets/d/1KHSwtKfqEQA_uDwsaqj42i4dF60orbnN_iaWSvIk4lY/edit#gid=0
