### ISSUE TITLE
Inconsistencies across environment installation instructions ? 

### ISSUE THREAD

**Issue by emileten** [MAAP-Project/stac_ipyleaflet#38]
Should this line in the README : 

`Requirements : python, pip, jupyter lab, virtualenv, node>=12.0.0`

be changed to : 

`Requirements : jupyter lab, node>=12.0.0`

(removing virtualenv, python and pip)

Because : 

- in the conda installation instruction we're installing a python version, and that ships with pip
- we are not using virtualenv in the instructions at all

**Comment by emileten** [comment]
@abarciauskas-bgse what do you think?

**Comment by abarciauskas-bgse** [comment]
👍🏽 seems reasonable
