### ISSUE TITLE
Milestone 2: Design Review

### ISSUE THREAD

**Issue by zacharyDez** [MAAP-Project/stac_ipyleaflet#42]
## Description

This milestone issue is created to track the progress of Milestone 2: Design Review. The goal of this milestone is to conduct a review of the project's design phase and ensure that it aligns with the project goals and objectives.

**Date:** [insert date]

## Agenda

- Presentation of the design concepts and prototypes
- Discussion of the strengths and weaknesses of the design approach
- Identification of areas for improvement and refinement
- Review of the project plan and timeline, if necessary

## Deliverables

- Summary of crucial feedback and recommendations from the design review
- Revised design concepts and prototypes, if necessary
- Updated project plan and timeline, if necessary

This milestone issue will be considered closed once the review has been successfully conducted, and all the deliverables have been completed.

**Comment by heidimok** [comment]
Update May 1, 2023:
![image](https://user-images.githubusercontent.com/10764915/235521552-802aacdc-549a-4ba1-b9cc-19421763bb96.png)
The initial release changes are in the [Miro board ](https://miro.com/app/board/uXjVMTIQFLE=/?share_link_id=994057585912), option D.
