### ISSUE TITLE
Milestone 4: Future Scope Workshop

### ISSUE THREAD

**Issue by zacharyDez** [MAAP-Project/stac_ipyleaflet#44]
## Description

This milestone issue is created to track the progress of Milestone 4: Future Scope Workshop. The goal of this milestone is to identify and explore potential areas of future development and expansion for the project.

## Agenda

- Presentation of the current project status and achievements
- Brainstorming session to identify potential areas of future development and expansion
- Discussion of the feasibility and potential impact of the identified areas
- Prioritization of the identified areas based on strategic fit and impact
- Development of a high-level roadmap for future development and expansion
- Review of the project plan and timeline, if necessary

## Deliverables

- Summary of the identified areas of future development and expansion
- High-level roadmap for future development and expansion
- Revised project plan and timeline, if necessary

This milestone issue will be considered closed once the workshop has been successfully conducted, and all the deliverables have been completed.

**Comment by heidimok** [comment]
**Update May 8, 2023:**
- This is the deliverable that tracks what's in scope/out of scope for June release for discussion during the group meeting: https://docs.google.com/presentation/d/1XNMK0UoYqwYnzIee6wm__vDT_r6NHR4yG08xVYWhBHk/edit#slide=id.g2239a496c2c_0_0

**Agenda:**
1. Review document
2. Have discussions along the way *priority for technical discussions on dataset availability and documentation
3. Future scoped requests will be logged [here](https://docs.google.com/spreadsheets/d/1KHSwtKfqEQA_uDwsaqj42i4dF60orbnN_iaWSvIk4lY/edit#gid=0) (living document) and work in progress

**Comment by heidimok** [comment]
Tracked here as a new task: https://github.com/NASA-IMPACT/active-maap-sprint/issues/643
