### ISSUE TITLE
Epic: UWG Workshop

### ISSUE THREAD

**Issue by zacharyDez** [MAAP-Project/stac_ipyleaflet#54]
### Description

This epic aims to improve the documentation for stac_ipyleaflet and leafmap, two geospatial visualization tools used by MAAP, and ensure that they are user-friendly and comprehensive. The goal is to provide users with clear and concise documentation that helps them get started quickly and easily and allows them to make the most of the tools' features. To achieve this goal, we will present the tools and their corresponding documentation to the user working group in June and ask for their feedback and suggestions for improvement.

### Tasks

- Review and update the existing documentation for stac_ipyleaflet and leafmap, focusing on clarity, comprehensiveness, and ease of use.
- Create a presentation that introduces the tools and their features and provides an overview of the documentation.
- Present the tools and the documentation to the user working group in June and ask for their feedback and suggestions for improvement.
- Collect user feedback and suggestions and analyze them to identify common themes and areas for improvement.
- Use the feedback and suggestions to update the documentation and improve its user-friendliness and comprehensiveness.
- Publish the updated documentation and notify the user working group of the changes.

### Acceptance Criteria

- The existing documentation for stac_ipyleaflet and leafmap is reviewed and updated for clarity, comprehensiveness, and ease of use.
- A presentation that introduces the tools and their features and provides an overview of the documentation is created.
- The tools and the documentation are presented to the user working group in June.
- User feedback and suggestions are collected and analyzed to identify common themes and areas for improvement.
- The documentation is updated based on the user feedback and suggestions, and its user-friendliness and comprehensiveness are improved.
- The updated documentation is published, and the user working group is notified of the changes.

**Comment by zacharyDez** [comment]
@abarciauskas-bgse @emmalu @heidimok , updated based on Aimee's feedback for the timeline.

**Comment by emmalu** [comment]
Noting that the WUG meeting is schedule for **June 12-14**.

**Comment by heidimok** [comment]
Done - result was a spreadsheet / roadmap of features: https://docs.google.com/spreadsheets/d/1KHSwtKfqEQA_uDwsaqj42i4dF60orbnN_iaWSvIk4lY/edit#gid=0
