### ISSUE TITLE
DIY Code - User should be able to visualize a raster file in their workspace

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/stac_ipyleaflet#6]
If users have a local COG, they should be a able to add it as a layer in the workspace.

We should first try using https://github.com/banesullivan/localtileserver to visualize local files.

We can just add a simple file browser tool widget so users can select a local file and add it as a layer which calls the localtileserver

Follow ups
- User can create a map layer from multiple files in their workspace
- Users can visualize files in a bucket in their workspace using titiler.maap-project.org - better form performance? this could be useful for mosaicing
- Extension idea (which may be a separate extension project): create right click on 1 or more files to add as layers. This could use the same functionality as built in this ticket but provide a shortcut in the file explorer. Would probably use https://jupyterlab.readthedocs.io/en/latest/api/modules/filebrowser.html and specifically `IFileBrowserFactor`. There is some example code https://github.com/abarciauskas-bgse/jlab_viz_ext/blob/main/src/index.ts#L21-L72 and in https://github.com/MAAP-Project/maap-jupyter-ide/search?q=ifilebrowserfactory

**Comment by heidimok** [comment]
Planned for `FY23.4`. Reference column `Number` `6` in the [MAAP-ipleaflet-DevRoadmap](https://docs.google.com/spreadsheets/d/1KHSwtKfqEQA_uDwsaqj42i4dF60orbnN_iaWSvIk4lY/edit#gid=0)

**Comment by emmalu** [comment]
stac ipyleaflet version: for release 0.3.0
Python version: python >= 3.9 (some of the widgets are incompatible at v 3.8)
Reference column Number 6 in the [MAAP-ipyleaflet-DevRoadmap](https://docs.google.com/spreadsheets/d/1KHSwtKfqEQA_uDwsaqj42i4dF60orbnN_iaWSvIk4lY/edit#gid=0)

**Comment by emmalu** [comment]
#### Sprint 23.4.2 Update
Works well in localhost, but is incompatible in ADE environment given the localtileserver's use of `127.0.0.1` URL to local tile. Trying to find a work-around.

**Comment by emmalu** [comment]
Was able to resolve using titiler - since local assets with MAAP and VEDA environments are in s3 buckets that are accessible via URL. https://github.com/MAAP-Project/stac_ipyleaflet/pull/110
