### ISSUE TITLE
Ability to filter STAC data by COGs

### ISSUE THREAD

**Issue by heidimok** [MAAP-Project/stac_ipyleaflet#66]
* stac ipyleaflet version: for release `0.3.0`
* Python version: python `>= 3.9` (some of the widgets are incompatible at v 3.8)
* Reference column `Number` `16` in the [MAAP-ipyleaflet-DevRoadmap](https://docs.google.com/spreadsheets/d/1cFQ0AQv94NSOBlTdolpb0aafQ0qNm78e7P9La7ClxHc/edit#gid=797015310)

## Context
Release `0.2.0` of stac_ipyleaflet allows users to select a collection from the STAC data catalog.
![image](https://github.com/MAAP-Project/stac_ipyleaflet/assets/10764915/96379dd7-a581-42b7-8a03-46845a3e16f9)
![image](https://github.com/MAAP-Project/stac_ipyleaflet/assets/10764915/2bfd1262-7c95-4226-9b2c-70eabd570bb0)

## Problem
Many of the collections don't have COGs, and as a result won't have anything visual to display on the map. It can be frustrating to click around without knowing which collections will have a visual output.
![image](https://github.com/MAAP-Project/stac_ipyleaflet/assets/10764915/57f2f56d-32f4-44f2-8c94-7dcdaacd199e)

## Acceptance Criteria
- [x] UI that allows users to filter STAC data catalog by items that actually have something visual (COGS) to display on map

**Comment by sandrahoang686** [comment]
I will be taking this ticket to get started

**Comment by heidimok** [comment]
Just contributing an idea from a UI perspective as I'm working through broader design changes. Here's one possible way to extend the current design with a checkbox. 
- The default would be checked
- The text could say something like "Only show displayable items"
![image](https://github.com/MAAP-Project/stac_ipyleaflet/assets/10764915/7b8e70df-25db-41fe-b300-8e0384aba3cd)

**Comment by emmalu** [comment]
> **Question** - is the filter at the collections level or the items level?
> 
> *

I believe it's both, although what's missing in the current build is at the Collections level.

**Comment by emmalu** [comment]
This is reading from the `item_assets` property on the selected Catalog `Collection`.
