### ISSUE TITLE
Deploy and test in the ADE workspace

### ISSUE THREAD

**Issue by abarciauskas-bgse** [MAAP-Project/stac_ipyleaflet#7]
Once the pypi package is published, we should try adding it to or creating a new maap-workspace image so it can be used in the MAAP ADE

**Comment by anisbhsl** [comment]
Still getting the same message: `Loading widget...` 
This is probably `ipywidget` not supported by our `jupterlab` version.

**Comment by abarciauskas-bgse** [comment]
@wildintellect did this in DIT 🎉 so closing
