### ISSUE TITLE
Updated Documentation for Release 0.3.0

### ISSUE THREAD

**Issue by heidimok** [MAAP-Project/stac_ipyleaflet#72]
- stac ipyleaflet version: for `release 0.3.0`
- Python version: `python >= 3.9` (some of the widgets are incompatible at v 3.8)
- Reference column `Number 37` in the [MAAP-ipyleaflet-DevRoadmap](https://docs.google.com/spreadsheets/d/1cFQ0AQv94NSOBlTdolpb0aafQ0qNm78e7P9La7ClxHc/edit#gid=797015310)

## Context
[Documentation was written for Release 0.2.0](https://docs.maap-project.org/en/develop/technical_tutorials/visualization/stac_ipyleaflet.html) of this library (currently still in dev and not production within the MAAP Docs) and as we work on the next release we'll need to make updates. 

## Problem
Upon releasing 0.3.0, things will be out of date. Additionally, we are also making this library available in the VEDA JupyterHub which means that we'll need to either:
- Centralize documentation or
- Update MAAP documentation and duplicate it within VEDA documentation

## Acceptance Criteria
- [ ] Updated documentation for release 0.3.0 available for both MAAP and VEDA

**Comment by emmalu** [comment]
Documentation updates:
- [ ] Multiple STAC catalogs
- [ ] Collections filter

**Comment by heidimok** [comment]
## Updating this issue's Acceptance Criteria 
(Based group chat with @emmalu and @wildintellect)

- [ ] Decision on where the new stac_ipyleaflet documentation is going to be, how it's going to be structured (things shared included https://www.mkdocs.org/ or https://quarto.org/)
- [ ] Updated documentation for release 0.3.0. Refer to feature list above. But as a baseline:
  - [ ] Content from the [previous MAAP documentation](https://docs.maap-project.org/en/develop/technical_tutorials/visualization/stac_ipyleaflet.html) for Release 0.2
  - [ ] New Interact (inspect) tool 
  - [ ] New Collections filter for COGs
  - [ ] DIY code guidance on the features we were not able to implement yet
    - [ ] https://github.com/MAAP-Project/stac_ipyleaflet/issues/85
    - [ ] https://github.com/MAAP-Project/stac_ipyleaflet/issues/6
- [ ] For existing MAAP documentation, update https://docs.maap-project.org/en/develop/technical_tutorials/visualization/stac_ipyleaflet.html with with 'Interact' functionality and link to new documentation for further/ongoing updates.
- [ ] For VEDA, add link in existing VEDA documentation to the new stac_ipyleaflet documentation

**Comment by heidimok** [comment]
VEDA documentation: https://nasa-impact.github.io/veda-docs/notebooks/tutorials/stac_ipyleaflet.html

**Comment by heidimok** [comment]
Decision to have a README notes pointing to other documentation is good enough to close issue.

**Comment by emmalu** [comment]
https://github.com/MAAP-Project/stac_ipyleaflet/pull/110
